### ISSUE TITLE
加上 dns-prefetch 算么

### ISSUE THREAD

**Issue by huanglong** [thx/html-code-guide#2]
当前页面需要获取多个子域名的图片，当前页面可能跳转后页面中包含，而本页面中未包含的域名，js 里会发起跳转的域名，做 DNS 预获取。

而本页面已经有 a 链接的，则不需要做 dns prefetch，chrome 会自动扫描，用法就一句：

```
<link rel="dns-prefetch" href="//cyj.me">
```

**Comment by yisibl** [comment]
CC @dotnil

**Comment by dotnil** [comment]
+1 good one

g.tbcd.cn 不支持 https，应该用得少了；gtms01234 一般活动页面才会有把；gw.alicdn.com 干嘛的

**Comment by yisibl** [comment]
MSDN:https://msdn.microsoft.com/zh-cn/library/dn265039(v=vs.85).aspx
segmentfault: [预加载系列一：DNS Prefetching 的正确使用姿势](http://segmentfault.com/a/1190000003944417)

**Comment by yisibl** [comment]
@huanglong @dotnil 请帮忙审阅。

**Comment by dotnil** [comment]
我觉得寻常页面没必要加了。

p.s. 第二篇文章的作者我认识诶

**Comment by yisibl** [comment]
@dotnil OK，我补充一下使用场景。

**Comment by huanglong** [comment]
赞，这个在特定场景下用就行，只有一个的活动页面这种是没必要的

**Comment by delai** [comment]
@dotnil 哈哈，你呀~

**Comment by dotnil** [comment]
@delai :smile:

**Comment by luckydrq** [comment]
:100:
